# Generated by Django 5.2 on 2025-04-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_posts_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
